GET http://localhost:3001/tracks HTTP/1.1


###
DELETE http://localhost:3001/tracks/177 HTTP/1.1


###
POST http://localhost:3001/tracks/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

playlist_id=3&title=gvhbjnj&uri=dfcghvjhhb&master_id=12434

